{
 "title": "Admin Panel",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "item_filter", "label": "Item Filter", "query": "Anom" },
   { "name": "fluid_filter", "label": "Fluid Filter", "query": "disabled" },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "select cpuname,last(busy) from cpus where time > NOW() - 5m group by cpuname"
    }
   }
  ]
 },
 "panels": [
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wireless EU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "measurement": "energy",
     "select": [
      [
       { "params": [ "wirelessf" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wireless EU/t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "measurement": "energy",
     "select": [
      [
       { "params": [ "wirelessf" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 20" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Antimatter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Naqfuel",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "fluid::tag" ], "type": "tag" }
     ],
     "measurement": "fluids",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "fluid::tag",
       "operator": "=",
       "value": "Naquadah Based Liquid Fuel MkVI (Depleted)"
      }
     ]
    }
   ]
  },
  {
   "title": "Stable inputs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "fluid::tag" ], "type": "tag" }
     ],
     "measurement": "fluids",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "fluid::tag", "operator": "=", "value": "Protomatter" },
      { "condition": "OR", "key": "fluid::tag", "operator": "=", "value": "Molten Shirabon" },
      { "condition": "OR", "key": "fluid::tag", "operator": "=", "value": "Tachyon Rich Temporal Fluid" },
      { "condition": "OR", "key": "fluid::tag", "operator": "=", "value": "Molten Eternity" },
      { "condition": "OR", "key": "fluid::tag", "operator": "=", "value": "Molten Superconductor Base UMV" }
     ]
    }
   ]
  },
  {
   "title": "Fluids",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fluids (Filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "query": "SELECT \"amount\" FROM \"fluids\" WHERE \"fluid\"::tag =~ /${fluid_filter}/ AND $timeFilter GROUP BY \"fluid\"::tag",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "fluid::tag", "operator": "!=", "value": "Water" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Waterline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grade 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "fluid::tag", "operator": "=", "value": "Filtered Water (Grade 1)" }
       ]
      }
     ]
    },
    {
     "title": "Grade 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "fluid::tag", "operator": "=", "value": "Ozonated Water (Grade 2)" }
       ]
      }
     ]
    },
    {
     "title": "Grade 3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "fluid::tag", "operator": "=", "value": "Flocculated Water (Grade 3)" }
       ]
      }
     ]
    },
    {
     "title": "Grade 4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "fluid::tag", "operator": "=", "value": "pH Neutralized Water (Grade 4)" }
       ]
      }
     ]
    },
    {
     "title": "Grade 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "fluid::tag",
         "operator": "=",
         "value": "Extreme-Temperature Treated Water (Grade 5)"
        }
       ]
      }
     ]
    },
    {
     "title": "Grade 6",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "fluid::tag",
         "operator": "=",
         "value": "Ultraviolet Treated Electrically Neutral Water (Grade 6)"
        }
       ]
      }
     ]
    },
    {
     "title": "Grade 7",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "fluid::tag",
         "operator": "=",
         "value": "Degassed Decontaminant-Free Water (Grade 7)"
        }
       ]
      }
     ]
    },
    {
     "title": "Grade 8",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "fluid::tag" ], "type": "tag" }
       ],
       "measurement": "fluids",
       "select": [
        [
         { "params": [ "amount" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "fluid::tag",
         "operator": "=",
         "value": "Subatomically Perfect Water (Grade 8)"
        }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Items (Filtered)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "item::tag" ], "type": "tag" }
     ],
     "measurement": "items",
     "query": "SELECT \"amount\" FROM \"items\" WHERE (\"item\"::tag =~ /${item_filter}/) AND $timeFilter GROUP BY \"item\"::tag",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "item::tag", "operator": "=~", "value": "/^$item_filter$/" }
     ]
    }
   ]
  },
  { "title": "Crafting CPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Activity",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 12, "x": 6, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cpuname::tag" ], "type": "tag" }
     ],
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crafting CPU $cpu",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "repeat": "cpu",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "craftingItem" ], "type": "field" }
      ],
      [
       { "params": [ "craftingCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpuname::tag", "operator": "=~", "value": "/^$cpu$/" }
     ]
    }
   ]
  }
 ]
}